services:
  trinetra-enterprises:
    build:
      context: .
      dockerfile: Dockerfile
    image: trinetra-enterprises:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
